[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_calc = "2hcHkZohEc5BwoXUs3ohSBWYr6CxnyfdrNBGigjzsGn7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/brandon.johnson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
